version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/master-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "ci-cd"

  - package-ecosystem: "docker"
    directory: "/master-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    labels:
      - "docker"
